services:
  - type: web
    name: bookit-backend
    runtime: node
    buildCommand: npm run render-postbuild
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # Set this in Render dashboard
      - key: PORT
        value: 10000